# Generated by Django 4.0.5 on 2022-07-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('other', 'Разное'), ('keyboard', 'Клавиатура'), ('block', 'Блок питания'), ('matrix', 'Матрица'), ('battery', 'Батарейка')], default='other', max_length=50, verbose_name='Категория'),
        ),
    ]
