# Generated by Django 4.0.5 on 2022-08-02 05:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт в Корзине',
                'verbose_name_plural': 'Продукты в Корзине',
                'db_table': 'ProductInCart',
            },
        ),
    ]
