# Generated by Django 4.0.5 on 2022-08-02 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productincart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='balance',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
    ]
