# Generated by Django 4.0.5 on 2022-08-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_orderproduct_user_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInCart',
        ),
    ]
